imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    images_directory: '%kernel.project_dir%/web/uploads/images'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection:
        enabled: true
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: utf8mb4
#        options:
#            1002:  "SET NAMES 'utf8mb4'"
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    #host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    #spool: { type: memory }

sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: 'no-reply@test_blog.local'
        sender_name: 'test_blog robot'

fos_rest:
    allowed_methods_listener: true
#    body_listener: true
#    view:
#      view_response_listener: true
    serializer:
        serialize_null: true
#    body_converter:
#        enabled: true
    format_listener:
        rules:
            - { path: '^/api/v1/blogs/',  priorities: ['html', 'json'], fallback_format: json, prefer_extension: true }
            - { path: '^/api',  priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }

jms_serializer:
    property_naming:
        separator:  _
        lower_case: true
#    metadata:
#        cache: file
#        debug: "%kernel.debug%"
#        file_cache:
#            dir: "%kernel.cache_dir%/serializer"
#        directories:
#            AppBundle:
#                namespace_prefix: AppBundle
#                path: %kernel.root_dir%/config/serializer/AppBundle
#        auto_detection: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false # Version >= 1.2, possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    custom_template: ~ # Version >= 1.2, path to your custom migrations template

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        #template: KnpMenuBundle::menu.html.twig
        template: 'partials/menu.html.twig'
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

knp_paginator:
    page_range: 3
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: 'partials/blog_pagination.html.twig'
        #pagination: KnpPaginatorBundle:Pagination:sliding.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig