<?php
/**
 * Created by PhpStorm.
 * User: sovkutsan
 * Date: 2/15/18
 * Time: 1:58 PM
 */

namespace AppBundle\Admin;

use AppBundle\Entity\Setting;
use AppBundle\Utils\QueryHelper;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;

/**
 * CRUD for key-value settings pairs
 * Class SettingsAdmin
 * @package AppBundle\Admin
 */
class SettingsAdmin extends AbstractAdmin
{

    public function preUpdate($object)
    {
        //parent::preUpdate($object); // TODO: Change the autogenerated stub
    }

    public function configureFormFields(FormMapper $form)
    {

        /**
         * @var Setting $obj
         */
        /*$obj = $this->getSubject();
        if (!$obj->isNew()) {
            $value = $obj->getValue();
            $decoded = json_decode($value);
            if (is_object($decoded)) {
                $form->add('skey', 'text');

                foreach ($decoded as $k => $v) {
                    $form->add('value[]', 'text');
                }

                $form->add('value', 'text');
                return;
                print_arr($value);
                print_die($decoded);
                die;
            }

        }*/

        $form
            ->add('skey', 'text')
            ->add('value', 'text');
    }

    public function configureDatagridFilters(DatagridMapper $filter)
    {
        $filter
            ->add('skey')
            ->add('value');
    }

    public function configureListFields(ListMapper $list)
    {
        $list
            ->addIdentifier('skey');
    }

    public function toString($object)
    {
        /**
         * @var Setting $object
         */
        if (null !== $object) {
            return $object->getSkey();
        }
        return 'Setting';
    }
}